apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - port: 9200
      name: http
      targetPort: 9200
    - port: 9300
      name: binary
      targetPort: 9300
  selector:
    deploymentconfig: cegeka-elasticsearch
name: elasticsearch
