apiVersion: v1
data:
  elasticsearch.yml: |
    network.host: _eth0_
    discovery.type: single-node
    #bootstrap.memory_lock: true
    cluster.name: ${CLUSTER_NAME}
kind: ConfigMap
metadata:
  name: elasticsearch-config
