apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: cegeka-elasticsearch
  name: cegeka-elasticsearch
spec:
  replicas: 1
  selector:
    app: cegeka-elasticsearch
    deploymentconfig: cegeka-elasticsearch
  template:
    metadata:
      labels:
        app: cegeka-elasticsearch
        deploymentconfig: cegeka-elasticsearch
    spec:
      containers:
        - env:
            - name: CLUSTER_NAME
              value: default-cluster-name
            - name: ES_HOME
              value: /usr/share/elasticsearch/
            - name: ES_JAVA_OPTS
              value: >-
                -Xms512m -Xmx512m
                -XX:HeapDumpPath=/elasticsearch/persistent/hdump.prof
                -Dsg.display_lic_none=false
                -Dio.netty.recycler.maxCapacityPerThread=0
                -Dio.netty.allocator.type=unpooled
                -Djdk.tls.ephemeralDHKeySize=2048
                -Des.path.home=/usr/share/elasticsearch
          image: >-
            __IS__:latest
          imagePullPolicy: Always
          name: cegeka-elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
            - mountPath: /usr/share/java/elasticsearch/config/
              name: volume-3fkxl
            - mountPath: /etc/podinfo
              name: podinfo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: elasticsearch-data
        - configMap:
            defaultMode: 420
            name: elasticsearch-config
          name: volume-3fkxl
        - emptyDir: {}
          name: podinfo
  test: false
